### 토큰 발급
POST http://localhost:8080/api/auth/dev-token?email=me@local.test&name=Me

> {%
    client.test("issue token", function() {
        client.global.set("token", response.body.jwt);
    });
%}

### 카테고리 생성
POST {{host}}/api/category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "parentCategoryId": 1,
  "name": "청년도약계좌",
  "categoryType": "INCOME",
  "imageUrl": "1",
  "investmentYn": "N",
  "useYn": "Y"
}

### 카테고리 수정
PUT {{host}}/api/category/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "적금변경",
  "categoryType": "EXPENSE",
  "imageUrl": "1"
}

### 카테고리 리스트 조회


### 카테고리 단건 조회
GET {{host}}/api/category/1
Authorization: Bearer {{token}}
Content-Type: application/json

### 카테고리 사용여부 변경