### 토큰 발급
POST http://localhost:8080/api/auth/dev-token?email=me@local.test&name=Me

> {%
    client.test("issue token", function() {
        client.global.set("token", response.body.jwt);
    });
%}

### 아이템 생성
POST {{host}}/api/item
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "categoryId": 2,
  "paymentId": 3,
  "amount": 1000,
  "occurredAt": "2025-10-08T14:30:00",
  "memo": "메모"
}

### 아이템 리스트 조회
GET {{host}}/api/item
Authorization: Bearer {{token}}
Content-Type: application/json

### 아이템 단건 조회
GET {{host}}/api/item/1
Authorization: Bearer {{token}}
Content-Type: application/json

### 투자집계 생성
POST {{host}}/api/invest-setting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "categoryId": 2
}