### 토큰 발급
POST http://localhost:8080/api/auth/dev-token?email=me@local.test&name=Me

> {%
    client.test("issue token", function() {
        client.global.set("token", response.body.jwt);
    });
%}

### 결제수단 생성
POST {{host}}/api/payment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "parentPaymentId": 7,
  "name": "월급통장",
  "paymentType": "ATM"
}

### 결제수단 수정
PUT {{host}}/api/payment/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "parentPaymentId": 6,
  "name": "체크카드",
  "paymentType": "ATM"
}

### 결제수단 사용여부 변경
PATCH {{host}}/api/payment/3/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "useYn": "N"
}


### 결제수단 리스트 조회
GET {{host}}/api/payment
Authorization: Bearer {{token}}
Content-Type: application/json

### 결제수단 단건 조회
GET {{host}}/api/payment/7
Authorization: Bearer {{token}}
Content-Type: application/json